services:

  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend-test:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    command: npm run lint
    restart: 'no'
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3001:3000
    healthcheck:
      interval: 10s
      timeout: 2s
      start_period: 15s
      retries: 5
      test: node healthcheck.js

  frontend-auth-test:
    build:
      context: auth
      dockerfile: ./auth/Dockerfile.frontend
    command: yarn test:microfrontend
    restart: 'no'
    environment:
          CI: true

  frontend-auth:
    build:
      context: auth
      dockerfile: ./auth/Dockerfile.frontend
    ports:
      - 8083:8083
    depends_on:
      backend:
        condition: service_healthy

  frontend-card-test:
    build:
      context: card
      dockerfile: ./card/Dockerfile.frontend
    command: yarn test:microfrontend
    restart: 'no'
    environment:
          CI: true

  frontend-card:
    build:
      context: card
      dockerfile: ./card/Dockerfile.frontend
    ports:
      - 8081:8081
    depends_on:
      backend:
        condition: service_healthy

  frontend-profile-test:
    build:
      context: profile
      dockerfile: ./profile/Dockerfile.frontend
    command: yarn test:microfrontend
    restart: 'no'
    environment:
          CI: true

  frontend-profile:
    build:
      context: profile
      dockerfile: ./profile/Dockerfile.frontend
    ports:
      - 8082:8082
    depends_on:
      backend:
        condition: service_healthy

  frontend-general-test:
    build:
      context: general
      dockerfile: ./general/Dockerfile.frontend
    command: yarn test:microfrontend
    restart: 'no'
    environment:
          CI: true

  frontend-general:
    build:
      context: general  
      dockerfile: ./general/Dockerfile.frontend
    ports:
      - 8082:8082
    depends_on:
      backend:
        condition: service_healthy